/**
 * 各匯入格式的欄位位置（需求規格附錄 A）。欄位序號從 1 起算。
 *
 * 解析器與合成樣本產生器共用這一份表（設計決策 7.4），兩邊不會各自寫一次欄位序號。
 * `src/import/formats.ts` 負責驗證欄數與關鍵表頭，這裡負責「哪個欄位在第幾欄」，
 * 也含解析器會讀、但表頭還不驗證的欄位（例如繁殖牝馬總表的 `国`）。
 */

export const BROODMARE_COLUMNS = {
  name: 1,
  country: 2,
  age: 3,
  sp: 4,
  st: 5,
  power: 6,
  quickness: 7,
  guts: 8,
  flexibility: 9,
  spirit: 10,
  wisdom: 11,
  health: 12,
  subParamTotal: 13,
  kodashi: 16,
  turf: 18,
  dirt: 19,
  distance: 23,
  vitality: 27,
  breedingYears: 37,
  breedingCount: 38,
  sire: 43,
  sireSystem: 44,
  dam: 45,
  femaleLine: 46,
  farm: 48,
  status: 49,
  matedStallion: 50,
  specialMating: 52,
  historicalNo: 56,
  abilityNo: 57,
  horseNo: 58,
  baseName: 59,
} as const;

export const STALLION_COLUMNS = {
  name: 1,
  country: 2,
  age: 3,
  sp: 4,
  st: 5,
  power: 6,
  quickness: 7,
  guts: 8,
  flexibility: 9,
  spirit: 10,
  wisdom: 11,
  health: 12,
  subParamTotal: 13,
  kodashi: 16,
  turf: 18,
  dirt: 19,
  distance: 23,
  sireSystem: 33,
  starts: 35,
  wins: 36,
  studFee: 37,
  earnings: 42,
  gradedWins: 43,
  g1Wins: 44,
  sire: 49,
  dam: 50,
  femaleLine: 51,
  bredCountry: 52,
  farm: 53,
  specialMating: 54,
  active: 56,
  historical: 57,
  historicalNo: 58,
  abilityNo: 59,
  horseNo: 60,
  baseName: 62,
} as const;

export const JAN2YO_COLUMNS = {
  name: 1,
  country: 2,
  age: 3,
  sex: 4,
  sp: 5,
  st: 6,
  power: 8,
  quickness: 9,
  guts: 10,
  flexibility: 11,
  spirit: 12,
  wisdom: 13,
  health: 14,
  subParamTotal: 15,
  turf: 17,
  dirt: 18,
  distance: 19,
  sireSystem: 32,
  kodashi: 35,
  sire: 51,
  dam: 52,
  femaleLine: 53,
  bredCountry: 62,
  bredFarm: 63,
  owner: 64,
  farm: 65,
  historical: 71,
  historicalNo: 73,
  abilityNo: 74,
  horseNo: 75,
  baseName: 77,
} as const;

export const APR_FOALS_COLUMNS = {
  name: 1,
  age: 3,
  sex: 4,
  sp: 5,
  st: 6,
  power: 8,
  quickness: 9,
  guts: 10,
  flexibility: 11,
  spirit: 12,
  wisdom: 13,
  health: 14,
  subParamTotal: 15,
  turf: 17,
  dirt: 18,
  distance: 27,
  kodashi: 28,
  sire: 46,
  sireSystem: 47,
  dam: 48,
  femaleLine: 49,
  bredFarm: 51,
  owner: 52,
  farm: 53,
  historicalNo: 57,
  abilityNo: 58,
  horseNo: 59,
  baseName: 61,
} as const;

export type ColumnMap = Readonly<Record<string, number>>;

export type BroodmareColumn = keyof typeof BROODMARE_COLUMNS;
export type StallionColumn = keyof typeof STALLION_COLUMNS;
export type Jan2yoColumn = keyof typeof JAN2YO_COLUMNS;
export type AprFoalsColumn = keyof typeof APR_FOALS_COLUMNS;
